on:
  release:
    types: [ released ]

name: Release docker image
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          DOCKER_IMAGE_TAG=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          echo "DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG" >> $GITHUB_ENV
      - uses: docker/login-action@v1
        with:
          username: roobre
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        run: |
          docker build . -t roobre/reroller:${DOCKER_IMAGE_TAG}
          docker tag roobre/reroller:${DOCKER_IMAGE_TAG} roobre/reroller:latest
      - name: Push docker image
        run: |
          docker push roobre/reroller:${DOCKER_IMAGE_TAG}
          docker push roobre/reroller:latest
