on:
  release:
    types: [ released ]

name: Release docker image

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          DOCKER_IMAGE_TAG=$(echo "${{ github.event.release.tag_name }}" | sed 's/^v//')
          echo "DOCKER_IMAGE_TAG=$DOCKER_IMAGE_TAG" >> $GITHUB_ENV
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        run: |
          docker build . -t ${{ env.REGISTRY }}/${{ github.repository }}:${DOCKER_IMAGE_TAG}
          docker tag ${{ env.REGISTRY }}/${{ github.repository }}:${DOCKER_IMAGE_TAG} ${{ env.REGISTRY }}/${{ github.repository }}:latest
      - name: Push docker image
        run: |
          docker push ${{ env.REGISTRY }}/${{ github.repository }}:${DOCKER_IMAGE_TAG}
          docker push ${{ env.REGISTRY }}/${{ github.repository }}:latest
